name: Publish NPM
on:
    release:
        types:
            - published
    push:
        paths:
            - .github/workflows/publish-npm.yml
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Performing Repository Checkout
              uses: actions/checkout@v2

            - name: Performing Pnpm Install on Workspace
              uses: pnpm/action-setup@v2.1.0
              with:
                  version: 6.0.2
                  run_install: true

            - name: Transpiling TypeScript
              run: pnpx tsc

            - name: Publishing to NPM
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
